version: "3"

services:
  app:
    image: sawyer-ros:latest
    stdin_open: true
    tty: true
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
